index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::show' }

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

register:
    path: /register
    controller: App\Controller\RegistrationController::show

login:
    path: /login
    controller: App\Controller\LoginController::show

tos:
    path: /tos
    controller: App\Controller\TermsOfServiceController::show

faq:
    path: /faq
    controller: App\Controller\FrequentlyAskedQuestionsController::show

remindPassword:
    path: /remindPassword
    controller: App\Controller\RemindPasswordController::show
