index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::show' }

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

registration:
    path: /register
    controller: App\Controller\RegistrationController
