index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::show' }
anything:
    path:     /{mypath}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: / #change this to whatever path
        permanent: true
    requirements:
        mypath: ".+"